name       : haskell-th-abstraction
version    : 0.2.6.0
release    : 1
source     :
    - https://hackage.haskell.org/package/th-abstraction-0.2.6.0/th-abstraction-0.2.6.0.tar.gz : e52e289a547d68f203d65f2e63ec2d87a3c613007d2fe873615c0969b981823c
license    : ISC
component  : programming.haskell
summary    : This package normalizes variations in the interface for inspecting datatype information via Template Haskell so that packages and support a single, easier to use informational datatype while supporting many versions of Template Haskell.
description: |
    This package normalizes variations in the interface for inspecting datatype information via Template Haskell so that packages and support a single, easier to use informational datatype while supporting many versions of Template Haskell.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
